### ISSUE TITLE
https://www.mytesy.com/?do=get_dev don,t work

### ISSUE THREAD

**Issue by KPCKPCKPC** [benov84/homebridge-tesy-heater#1]
dear benov84,

the link https://www.mytesy.com/?do=get_dev doesn't work for me.
I only see a blank screen on firefox and on chrome an HTTP ERROR 500 message.
What am I doing wrong
Can you help me with that?

**Comment by benov84** [comment]
The link is working on my side. I don't know why you're getting the server error 500, maybe you must contact tesy support.
