### ISSUE TITLE
Get token url is not working

### ISSUE THREAD

**Issue by Seishin** [benov84/homebridge-tesy-heater#2]
I'm rising this issue once again since it was already asked last year (#1) but unfortunately, the issue was closed and not resolved... 

Maybe, the API has changed and the https://www.mytesy.com/?do=get_dev is no longer working. Since you, @benov84, are the developer of this plugin and have the knowledge, could you assist with another way to obtain the token?

**Comment by benov84** [comment]
Hi,
try this
https://www.mytesy.com/v3/api.php?do=get_dev

**Comment by Seishin** [comment]
It worked! Thank you! 🙇🏻
